name: btkproje
description: A Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
